### ISSUE TITLE
How do the new query be sent?

### ISSUE THREAD

**Issue by lionng429** [ProLoser/AngularJS-ORM#14]
I look through the codes and found that the `send` function of Socket is called only in `setupQueryStream`.

The active queries are passed to the stream, but it seems that they are not being sent out.

May I know how could it handle active query requests ??

**Comment by ProLoser** [comment]
Keep in mind that some of this code was theoretical, but this line would send the query to the server https://github.com/ProLoser/AngularJS-ORM/blob/master/modules/Socket.coffee#L26

**Comment by lionng429** [comment]
Thanks for the reply. I forgot this is put into the stream listeners.
