### ISSUE TITLE
Bower error

### ISSUE THREAD

**Issue by TimoSolo** [ProLoser/AngularJS-ORM#18]
[noob disclaimer]
Hi, I'm trying to install the bower dependencies on Mac OSX but get an error:
bower install    
bower not-cached    git://github.com/angular-ui/ui-utils.git#~1
bower resolve       git://github.com/angular-ui/ui-utils.git#~1
bower not-cached    git://github.com/angular-ui/ui-router.git#~1
bower resolve       git://github.com/angular-ui/ui-router.git#~1
bower not-cached    git://github.com/angular/bower-angular.git#~1.2.12
bower resolve       git://github.com/angular/bower-angular.git#~1.2.12
bower download      https://github.com/angular/bower-angular/archive/v1.2.28.tar.gz
bower extract       angular#~1.2.12 archive.tar.gz
bower resolved      git://github.com/angular/bower-angular.git#1.2.28
bower ENORESTARGET  No tag found that was able to satisfy ~1

any ideas? 

Is there a working demo or is it just pseudo code?

Thanks

**Comment by ProLoser** [comment]
This isn't a library, nor have I tested that it can execute, it's just pseudo-code. I give no guarantees that this exact code will run as-is.

I do know for the most part all of the syntax is valid, but for example I have no backend or sockets to connect to.
