### ISSUE TITLE
Commit workflow/tasks for transpilation, development server, etc.

### ISSUE THREAD

**Issue by justingreenberg** [ProLoser/AngularJS-ORM#19]
Very cool ideas! May I ask what tools you are using in the dev environment? Is it possible to commit your package.json as well as gulp/grunt/slush-file? The ES6 source is very helpful, however for someone who wants to quickly `git clone`, poke around with the demo to explore the ORM concepts presented, it would be awesome to be able to `npm install && gulp serve` :smile: 

Thanks again

**Comment by ProLoser** [comment]
This is all pseudocode. I am not even sure it will run without errors.

**Comment by ProLoser** [comment]
I will see what I can do

**Comment by ProLoser** [comment]
@justingreenberg I added my gulpfile and package.json, however they are completely untested and and tweaked. But at least this is the gulp code i use at my company FYI. I had mixed feelings about including it because i don't necessarily feel people should copy it, as it's not a "best practice"

**Comment by justingreenberg** [comment]
thank you @ProLoser, much appreciated
